version: '3.8'

services:
  apache:
    build:
      context: ./apis/passerelle  # Path to the Dockerfile for Apache
    ports:
      - "800:800"  # Expose port 80 for Apache
    depends_on:
      - crud_app
      # - node_app
    networks:
      - my_network

  crud_app:
    build:
      context: ./apis/crud  # Path to the Dockerfile for CRUD app
    ports:
      - "3001:3001"  # Expose port 3000 for the CRUD app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
